version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgresuser"
      POSTGRES_PASSWORD: "postgrespass"
      POSTGRES_DB: "inclusao_digital"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: